[package]
name = "connect4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c4_display = { path = "../c4_display" }
log = "0.4.14"
env_logger = "0.9.0"
rand = "0.8.4"
rppal = "0.13.1"